require('plugins')
require('options')
require('nvim-tree-config')
require('lualine-config')
require('bufferline-config')
require('treesitter-config')
require('autopairs-config')
require('cmp-config')
require("blankline-config")
require('mason-config')
require('keybindings')
require("format-config")
vim.cmd('colorscheme rose-pine')

